# Generated by Django 5.2.4 on 2026-01-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_age_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='assigned_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTION', 'Reception'), ('DOCTOR', 'Doctor'), ('LAB', 'Lab'), ('PHARMACY', 'Pharmacy'), ('CASUALTY', 'Casualty')], default='DOCTOR', max_length=20),
        ),
    ]
