# Generated by Django 5.2.4 on 2026-01-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_visit_assigned_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='assigned_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTION', 'Reception'), ('DOCTOR', 'Doctor'), ('LAB', 'Lab'), ('PHARMACY', 'Pharmacy'), ('BILLING', 'Billing'), ('CASUALTY', 'Casualty')], default='DOCTOR', max_length=20),
        ),
    ]
