# Generated by Django 5.2.4 on 2026-01-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_visit_assigned_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='registration_number',
            field=models.CharField(default='TEMP', help_text='Manual Registration Number', max_length=50, null=True, blank=True),
        ),
    ]
