# Generated by Django 5.2.4 on 2026-01-26 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_months',
            field=models.PositiveIntegerField(default=0, help_text='Months (0-11)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
