# Generated by Django 5.2.4 on 2026-01-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='expiry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='hsn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
