# Generated by Django 5.2.4 on 2026-01-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoiceitem_batch_invoiceitem_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='dosage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
