# Generated by Django 5.2.4 on 2026-01-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoiceitem_dosage_invoiceitem_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
