# Generated by Django 5.2.4 on 2026-01-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoiceitem_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='deducted_qty',
            field=models.IntegerField(default=0),
        ),
    ]
