# Generated by Django 5.2.4 on 2026-01-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoiceitem_deducted_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
