# Generated by Django 5.2.4 on 2026-01-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'Google Pay / UPI'), ('CARD', 'Card')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
