# Generated by Django 5.2.4 on 2026-01-14 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_visit_assigned_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasualtyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('transfer_path', models.TextField()),
                ('treatment_notes', models.TextField()),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casualty_logs', to='patients.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
