# Generated by Django 5.2.4 on 2026-01-24 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casualty', '0001_initial'),
        ('patients', '0005_alter_visit_assigned_role'),
        ('pharmacy', '0013_purchaseinvoice_cash_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasualtyServiceDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='casualtylog',
            name='vitals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CasualtyMedicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('administered_at', models.DateTimeField(auto_now_add=True)),
                ('med_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.pharmacystock')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casualty_medicines', to='patients.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CasualtyObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('planned_duration_minutes', models.PositiveIntegerField(default=60)),
                ('observation_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casualty_observations', to='patients.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CasualtyService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casualty_services', to='patients.visit')),
                ('service_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casualty.casualtyservicedefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
