# Generated by Django 5.2.4 on 2026-01-25 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casualty', '0002_casualtyservicedefinition_casualtylog_vitals_and_more'),
        ('pharmacy', '0014_pharmacyreturn_pharmacyreturnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casualtymedicine',
            name='med_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacystock'),
        ),
    ]
