import React, { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Pill, Plus, Search, ShoppingCart, AlertTriangle,
    Activity, User, Trash2, Printer, X, CheckCircle2,
    Clock, UploadCloud, FileText, Send, Eye, ChevronRight, PackagePlus, FileSpreadsheet
} from 'lucide-react';
import { Button, Input } from '../components/UI';
import Pagination from '../components/Pagination';
import api from '../api/axios';
import { useSearch } from '../context/SearchContext';
import { useToast } from '../context/ToastContext';
import { socket } from '../socket';

// --- Premium Tooltip ---
const ActionTooltip = ({ text, children }) => (
    <div className="group relative flex items-center justify-center">
        {children}
        <div className="absolute bottom-full mb-2 hidden group-hover:flex flex-col items-center z-[100] whitespace-nowrap animate-in fade-in zoom-in-95 duration-200">
            <span className="relative z-50 px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider rounded-lg shadow-xl bg-slate-900 text-white">
                {text}
                <span className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 rotate-45 bg-slate-900"></span>
            </span>
        </div>
    </div>
);

// --- Receipt Template ---
const ReceiptTemplate = ({ sale }) => (
    <div className="font-mono text-[10px] leading-relaxed uppercase text-slate-900 p-8">
        <div className="text-center space-y-1 mb-6">
            <h1 className="text-xl font-black tracking-widest uppercase">Revive Pharmacy</h1>
            <div className="flex items-center justify-center gap-4 text-[9px] font-bold text-slate-500">
                <span>LIC: KL-WYD-159132</span>
                <span>PH: +91 9496851538</span>
            </div>
            <p className="text-[9px] font-bold border-y border-slate-200 py-1 mt-2">Tax Invoice / Retail Bill</p>
        </div>

        <div className="grid grid-cols-2 gap-x-8 gap-y-1 border-b border-dashed border-slate-300 pb-4 mb-4">
            <div className="flex justify-between"><span>Bill Date</span> <span>: {new Date(sale.sale_date).toLocaleDateString()}</span></div>
            <div className="flex justify-between"><span>Invoice No</span> <span className="font-bold">: {sale.invoice_no || sale.id?.slice(0, 8).toUpperCase()}</span></div>
            <div className="flex justify-between"><span>Patient</span> <span>: {sale.patient?.full_name || 'Walk-In'}</span></div>
            <div className="flex justify-between"><span>Doctor</span> <span>: {sale.doctor?.username || '---'}</span></div>
        </div>

        <div className="grid grid-cols-12 gap-1 border-b border-slate-900 pb-1 mb-2 font-black text-[9px]">
            <span className="col-span-6">Item</span>
            <span className="col-span-2 text-center">Batch</span>
            <span className="col-span-1 text-center">Qty</span>
            <span className="col-span-3 text-right">Amount</span>
        </div>

        <div className="space-y-1 min-h-[100px]">
            {sale.details.map((item, idx) => (
                <div key={idx} className="grid grid-cols-12 gap-1 font-bold text-[9px]">
                    <span className="col-span-6 truncate">{item.name}</span>
                    <span className="col-span-2 text-center truncate">{item.batch_no}</span>
                    <span className="col-span-1 text-center">{item.qty}</span>
                    <span className="col-span-3 text-right">{(item.selling_price * item.qty).toFixed(2)}</span>
                </div>
            ))}
        </div>

        <div className="mt-4 pt-2 border-t border-dashed border-slate-300 space-y-1 font-black">
            <div className="flex justify-end gap-8 text-lg">
                <span>NET TOTAL:</span>
                <span>₹{Math.ceil(sale.total_amount).toFixed(2)}</span>
            </div>
        </div>

        <p className="text-center mt-8 text-[8px] text-slate-400">Get Well Soon • Generated by Revive CMS</p>
    </div>
);

const Pharmacy = () => {
    const { showToast } = useToast();

    // --- STATE ---
    const [activeTab, setActiveTab] = useState('inventory');
    const [loading, setLoading] = useState(false);

    // Inventory
    const [stockData, setStockData] = useState({ results: [], count: 0 });
    const [page, setPage] = useState(1);
    const [rowsPerPage, setRowsPerPage] = useState(50);
    const [selectedStockItem, setSelectedStockItem] = useState(null);
    const [suppliers, setSuppliers] = useState([]);
    const [filterSupplier, setFilterSupplier] = useState('');

    // POS
    const [cart, setCart] = useState([]);
    const [gstRate, setGstRate] = useState(0); // Default to 0% GST
    const [patientSearch, setPatientSearch] = useState('');
    const [patients, setPatients] = useState([]);
    const [selectedPatient, setSelectedPatient] = useState(null);
    const [doctorSearch, setDoctorSearch] = useState('');
    const [doctors, setDoctors] = useState([]);
    const [selectedDoctor, setSelectedDoctor] = useState(null);
    const [medSearch, setMedSearch] = useState('');
    const [medResults, setMedResults] = useState([]);
    const [lastSale, setLastSale] = useState(null);
    const [showPrintModal, setShowPrintModal] = useState(false);
    const [pendingVisits, setPendingVisits] = useState([]);

    // Purchases
    const [fileToUpload, setFileToUpload] = useState(null);
    const [selectedSupplier, setSelectedSupplier] = useState('');
    const [uploadLoading, setUploadLoading] = useState(false);
    const [uploadResult, setUploadResult] = useState(null);
    const [recentImports, setRecentImports] = useState([]);
    const [selectedImport, setSelectedImport] = useState(null);
    const [showAddSupplierModal, setShowAddSupplierModal] = useState(false);
    const [newSupplierName, setNewSupplierName] = useState('');
    const [showManualPurchaseModal, setShowManualPurchaseModal] = useState(false);
    const [manualInvoice, setManualInvoice] = useState({
        supplier: '', supplier_invoice_no: '', invoice_date: new Date().toISOString().split('T')[0], purchase_type: 'CASH', items: []
    });
    const [scannedBarcode, setScannedBarcode] = useState('');

    // --- FETCH FUNCTIONS ---
    const fetchStock = useCallback(async (showLoading = true) => {
        if (showLoading) setLoading(true);
        try {
            let url = `pharmacy/stock/?page=${page}`;
            if (rowsPerPage !== 'all') url += `&page_size=${rowsPerPage}`;
            if (filterSupplier) url += `&supplier=${filterSupplier}`;
            const { data } = await api.get(url);
            setStockData(data.results ? data : { results: data || [], count: data.length || 0 });
        } catch (err) { setStockData({ results: [], count: 0 }); }
        finally { if (showLoading) setLoading(false); }
    }, [page, rowsPerPage, filterSupplier]);

    const fetchSuppliers = useCallback(async () => {
        try {
            const { data } = await api.get('pharmacy/suppliers/');
            setSuppliers(Array.isArray(data) ? data : (data.results || []));
        } catch (err) { setSuppliers([]); }
    }, []);

    const fetchRecentImports = useCallback(async () => {
        try {
            const { data } = await api.get('pharmacy/purchases/');
            setRecentImports(Array.isArray(data) ? data : (data.results || []));
        } catch (err) { setRecentImports([]); }
    }, []);

    const fetchPendingVisits = useCallback(async (showLoading = false) => {
        if (showLoading) setLoading(true);
        try {
            const { data } = await api.get('reception/visits/?assigned_role=PHARMACY&status=OPEN');
            setPendingVisits(Array.isArray(data) ? data : (data.results || []));
        } catch (err) { setPendingVisits([]); }
        finally { if (showLoading) setLoading(false); }
    }, []);

    useEffect(() => {
        fetchStock(true); fetchSuppliers(); fetchPendingVisits(false); fetchRecentImports();
        // Global socket listener for prescriptions
        const onDoctorUpdate = (data) => { if (data.has_prescription) { fetchPendingVisits(false); showToast('info', 'New prescription received'); } };
        socket.on('doctor_notes_update', onDoctorUpdate);
        return () => { socket.off('doctor_notes_update', onDoctorUpdate); };
    }, []);

    // Auto-Refresh: Only on POS tab to avoid resetting filters in Inventory
    useEffect(() => {
        let interval;
        if (activeTab === 'pos') {
            interval = setInterval(() => {
                fetchPendingVisits(false);
            }, 4000); // 4 second reload as requested
        }
        return () => { if (interval) clearInterval(interval); };
    }, [activeTab, fetchPendingVisits]);

    useEffect(() => {
        if (activeTab === 'inventory') fetchStock();
        else if (activeTab === 'purchases') { fetchRecentImports(); fetchSuppliers(); }
        else if (activeTab === 'pos') fetchPendingVisits();
    }, [activeTab, fetchStock, fetchRecentImports, fetchSuppliers, fetchPendingVisits]);

    // --- LOGIC (Simplified for display, keeping original functionality) ---
    const searchPatients = async (q) => {
        setPatientSearch(q);
        if (q.length < 2) { setPatients([]); return; }
        try { const { data } = await api.get(`reception/patients/?search=${q}`); setPatients(data.results || data); } catch (err) { }
    };
    const searchDoctors = async (q) => {
        setDoctorSearch(q);
        if (q.length < 2) { setDoctors([]); return; }
        try { const { data } = await api.get(`users/management/doctors/?search=${q}`); setDoctors(data); } catch (err) { }
    };
    const searchMeds = async (q) => {
        setMedSearch(q);
        if (!q || q.length < 2) { setMedResults([]); return; }
        try { const { data } = await api.get(`pharmacy/stock/?search=${q}`); setMedResults(data.results || data || []); } catch (err) { setMedResults([]); }
    };
    const addToCart = (med) => {
        const existing = cart.find(item => item.med_id === med.med_id);
        const tps = med.tablets_per_strip || 1;

        // Calculate reduction if GST is applied
        let stripPrice = med.mrp;
        if (gstRate > 0) {
            const reductionAmount = med.mrp * (gstRate / 100);
            stripPrice = med.mrp - reductionAmount;
        }

        // Tablet Price
        const tabletPrice = stripPrice / tps;

        if (existing) {
            if (existing.qty < med.qty_available) setCart(cart.map(item => item.med_id === med.med_id ? { ...item, qty: item.qty + 1 } : item));
            else showToast('error', "Out of stock!");
        } else {
            setCart([...cart, {
                ...med,
                qty: 1,
                selling_price: tabletPrice, // Store per tablet price
                strip_price: stripPrice,
                gst_applied: gstRate,
                original_mrp: med.mrp
            }]);
        }
        setMedSearch(''); setMedResults([]);
    };
    const handleBarcodeStockIn = async (barcode) => {
        try {
            const { data } = await api.get(`pharmacy/stock/?search=${barcode}`);
            const existing = data.results?.[0];
            if (existing) {
                const newItem = { product_name: existing.name, barcode: existing.barcode, batch_no: '', expiry_date: '', qty: 1, free_qty: 0, purchase_rate: existing.purchase_rate || 0, ptr: existing.purchase_rate || 0, mrp: existing.mrp, manufacturer: existing.manufacturer, hsn: existing.hsn, tablets_per_strip: existing.tablets_per_strip || 10 };
                setManualInvoice(prev => ({ ...prev, items: [...prev.items, newItem] }));
                showToast('success', `Found: ${existing.name}`);
            } else {
                setManualInvoice(prev => ({ ...prev, items: [...prev.items, { product_name: '', barcode, batch_no: '', expiry_date: '', qty: 1, free_qty: 0, purchase_rate: 0, ptr: 0, mrp: 0, manufacturer: '', hsn: '', tablets_per_strip: 10 }] }));
                showToast('info', 'New product. Enter details.');
            }
            setScannedBarcode('');
        } catch (err) { console.error("Barcode lookup failed", err); }
    };
    const handleManualItemChange = (idx, field, value) => {
        const newItems = [...manualInvoice.items]; newItems[idx][field] = value; setManualInvoice(prev => ({ ...prev, items: newItems }));
    };
    const removeManualItem = (idx) => { setManualInvoice(prev => ({ ...prev, items: prev.items.filter((_, i) => i !== idx) })); };
    const submitManualPurchase = async () => {
        if (!manualInvoice.supplier || !manualInvoice.supplier_invoice_no || manualInvoice.items.length === 0) return showToast('error', 'Please fill all required fields.');
        try {
            // Convert Total Values to Unit Values for Backend
            const payload = {
                ...manualInvoice,
                items: manualInvoice.items.map(item => {
                    const qty = parseInt(item.qty) || 1;
                    return {
                        ...item,
                        purchase_rate: (parseFloat(item.purchase_rate) || 0) / qty, // Derive Unit Rate
                        ptr: (parseFloat(item.purchase_rate) || 0) / qty,
                        mrp: (parseFloat(item.mrp) || 0) / qty, // Derive Unit MRP
                    };
                })
            };
            setLoading(true); await api.post('pharmacy/purchases/', payload); showToast('success', 'Stock updated!'); setShowManualPurchaseModal(false); setManualInvoice({ supplier: '', supplier_invoice_no: '', invoice_date: new Date().toISOString().split('T')[0], purchase_type: 'CASH', items: [] }); fetchRecentImports(); fetchStock();
        } catch (err) { showToast('error', `Failed: ${err.response?.data?.detail || "Check fields"}`); } finally { setLoading(false); }
    };
    const calculateTotals = () => { const subtotal = cart.reduce((acc, item) => acc + (item.selling_price * item.qty), 0); return { subtotal, net: Math.ceil(subtotal) }; };
    useEffect(() => {
        if (cart.length > 0) {
            setCart(prevCart => prevCart.map(item => {
                const mrp = item.original_mrp || item.mrp;
                const tps = item.tablets_per_strip || 1;

                // Calculate reduction if GST is applied
                let newStripPrice = mrp;
                if (gstRate > 0) {
                    const reductionAmount = mrp * (gstRate / 100);
                    newStripPrice = mrp - reductionAmount;
                }

                const newTabletPrice = newStripPrice / tps;
                return {
                    ...item,
                    selling_price: newTabletPrice,
                    strip_price: newStripPrice,
                    gst_applied: gstRate,
                    original_mrp: mrp
                };
            }));
        }
    }, [gstRate]);
    const handleCheckout = async () => {
        if (cart.length === 0) return showToast('error', "Cart Empty");
        let visitId = selectedPatient?.v_id || null;
        if (!visitId && selectedPatient) { const matchInQueue = pendingVisits.find(v => v.patient === selectedPatient.id || (v.patient?.id === selectedPatient.id) || v.patient_name === selectedPatient.full_name); if (matchInQueue) visitId = matchInQueue.id || matchInQueue.v_id; }
        const payload = { visit: visitId, patient: selectedPatient?.p_id || selectedPatient?.id || null, items: cart.map(item => ({ med_stock: item.med_id || item.id, qty: item.qty, unit_price: parseFloat(item.selling_price.toFixed(2)), gst_percent: item.gst_applied || 0 })), payment_status: 'PENDING' };
        try { const { data } = await api.post('pharmacy/sales/', payload); setLastSale({ ...data, patient: selectedPatient, doctor: selectedDoctor, details: cart }); if (visitId) { await api.patch(`reception/visits/${visitId}/`, { status: 'CLOSED' }); fetchPendingVisits(); } setCart([]); setMedSearch(''); setMedResults([]); setSelectedPatient(null); setSelectedDoctor(null); showToast('success', 'Sent to Billing.'); } catch (err) { showToast('error', "Transaction failed"); }
    };
    const loadPrescription = async (visit) => {
        setSelectedPatient({ ...visit.patient, full_name: visit.patient_name, v_id: visit.id });
        if (visit.doctor_name) setSelectedDoctor({ username: visit.doctor_name, u_id: visit.doctor }); else setSelectedDoctor({ username: 'Referral', u_id: null });
        if (!visit.prescription) { showToast('info', 'No digital prescription.'); return; }
        setLoading(true); const newCart = [];
        try {
            const medNames = Object.keys(visit.prescription); for (const name of medNames) {
                const details = visit.prescription[name]; let qty = 1; const qtyMatch = details.match(/Qty:\s*(\d+)/i); if (qtyMatch) qty = parseInt(qtyMatch[1]); const { data } = await api.get(`pharmacy/stock/?search=${encodeURIComponent(name)}`); const results = data.results || data || []; const match = results.find(r => r.name.toLowerCase() === name.toLowerCase()) || results[0]; if (match) {
                    const tps = match.tablets_per_strip || 1;
                    const stripPrice = match.mrp; // Selling at MRP
                    const tabletPrice = stripPrice / tps;
                    newCart.push({ ...match, qty: qty, selling_price: tabletPrice, strip_price: stripPrice, gst_applied: gstRate, original_mrp: match.mrp });
                }
            } setCart(newCart); if (newCart.length > 0) showToast('success', 'Rx loaded');
        } catch (err) { console.error(err); } finally { setLoading(false); }
    };
    const handleFileChange = (e) => { if (e.target.files && e.target.files[0]) setFileToUpload(e.target.files[0]); };
    const handleConfirmUpload = async () => { if (!fileToUpload || !selectedSupplier) return; const formData = new FormData(); formData.append('file', fileToUpload); formData.append('supplier_name', selectedSupplier); setUploadLoading(true); try { const { data } = await api.post('pharmacy/bulk-upload/', formData, { headers: { 'Content-Type': 'multipart/form-data' } }); setUploadResult({ success: true, message: 'Upload Successful', details: `${data.items_processed} items processed.`, invoice: data.invoice_no }); showToast('success', 'Inventory updated'); if (activeTab === 'purchases') fetchRecentImports(); setFileToUpload(null); } catch (err) { showToast('error', 'Upload failed.'); setUploadResult({ success: false, message: 'Upload Failed', details: err.response?.data?.error || "Error uploading file." }); } finally { setUploadLoading(false); } };
    const handleSyncToTablets = async (item) => { if (!window.confirm(`This will multiply current stock (${item.qty_available}) by ${item.tablets_per_strip} to convert existing strip counts to tablets. Continue?`)) return; try { const newQty = item.qty_available * item.tablets_per_strip; await api.patch(`pharmacy/stock/${item.med_id || item.id}/`, { qty_available: newQty }); showToast('success', 'Stock corrected to tablets'); fetchStock(); setSelectedStockItem(null); } catch (err) { showToast('error', 'Update failed'); } };
    const handleAddSupplier = async (e) => { e.preventDefault(); try { await api.post('pharmacy/suppliers/', { supplier_name: newSupplierName }); fetchSuppliers(); setShowAddSupplierModal(false); setNewSupplierName(''); showToast('success', 'Supplier added'); } catch (err) { showToast('error', 'Failed to add supplier'); } };

    return (
        <div className="p-6 md:p-8 max-w-[1600px] mx-auto min-h-screen bg-[#F8FAFC] font-sans text-slate-900 flex flex-col overflow-hidden">

            {/* --- Top Header & Navigation --- */}
            <div className="flex justify-between items-center mb-8 shrink-0 no-print">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight text-slate-950 font-outfit uppercase">Pharmacy</h1>
                    <div className="flex items-center gap-6 mt-2">
                        {['inventory', 'pos', 'purchases'].map(tab => (
                            <button key={tab} onClick={() => setActiveTab(tab)} className={`pb-1 text-sm font-bold transition-all border-b-2 ${activeTab === tab ? 'text-blue-600 border-blue-600' : 'text-slate-400 border-transparent hover:text-slate-600'}`}>
                                {tab === 'pos' ? 'Billing Terminal (POS)' : tab.charAt(0).toUpperCase() + tab.slice(1)}
                            </button>
                        ))}
                    </div>
                </div>
                {activeTab === 'inventory' && (
                    <div className="flex gap-3">
                        <select className="bg-white border border-slate-200 text-slate-700 text-xs rounded-xl focus:ring-blue-500 focus:border-blue-500 block px-3 py-2 outline-none font-bold shadow-sm" value={filterSupplier} onChange={(e) => setFilterSupplier(e.target.value)}>
                            <option value="">Filter: All Suppliers</option>
                            {suppliers.map(s => <option key={s.id} value={s.id}>{s.supplier_name}</option>)}
                        </select>
                    </div>
                )}
            </div>

            {/* --- WORKSPACE AREA --- */}
            <div className="flex-1 min-h-0 bg-white rounded-[24px] border border-slate-100 shadow-sm overflow-hidden relative flex flex-col">

                {/* 1. INVENTORY TAB */}
                {activeTab === 'inventory' && (
                    <>
                        <div className="flex-1 overflow-auto">
                            <table className="w-full text-left border-collapse">
                                <thead className="bg-slate-50 sticky top-0 z-10 shadow-sm"><tr>{['Drug Name', 'Batch', 'Expiry', 'Total (Tab)', 'P.Rate', 'Sales Price/Tab', 'MRP', 'Action'].map(h => <th key={h} className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">{h}</th>)}</tr></thead>
                                <tbody className="divide-y divide-slate-50">
                                    {(stockData?.results || []).map(s => (
                                        <tr key={s.med_id} className="hover:bg-slate-50 transition-colors group">
                                            <td className="px-6 py-3"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center font-bold"><Pill size={14} /></div><div><p className="font-bold text-slate-900 text-sm">{s.name}</p><p className="text-[10px] font-bold text-slate-400 uppercase">{s.manufacturer || 'Generic'}</p></div></div></td>
                                            <td className="px-6 py-3 font-mono text-xs font-bold text-slate-600">{s.batch_no}</td>
                                            <td className="px-6 py-3 font-mono text-xs font-bold text-slate-600">{new Date(s.expiry_date).toLocaleDateString(undefined, { month: 'short', year: '2-digit' })}</td>
                                            <td className="px-6 py-3">
                                                <div className="flex flex-col">
                                                    <span className={`inline-flex items-center px-2 py-0.5 rounded-md text-xs font-bold ${s.qty_available < 10 ? 'bg-red-50 text-red-600' : 'bg-emerald-50 text-emerald-600'}`}>
                                                        {s.qty_available} TAB
                                                    </span>
                                                    <span className="text-[10px] font-bold text-slate-400 mt-1 uppercase">
                                                        ({Math.floor(s.qty_available / (s.tablets_per_strip || 1))} STR, {s.qty_available % (s.tablets_per_strip || 1)} TAB)
                                                    </span>
                                                </div>
                                            </td>
                                            <td className="px-6 py-3 font-bold text-sm text-slate-500">
                                                <div className="flex flex-col">
                                                    <span>₹{s.purchase_rate} <span className="text-[8px] text-slate-400 uppercase">/Strip</span></span>
                                                    <span className="text-[10px] text-slate-400 font-normal">₹{(s.purchase_rate / (s.tablets_per_strip || 1)).toFixed(2)} /Tab</span>
                                                </div>
                                            </td>
                                            <td className="px-6 py-3 font-black text-sm text-blue-600">
                                                ₹{(s.selling_price / (s.tablets_per_strip || 1)).toFixed(2)}
                                                <span className="block text-[8px] text-slate-400 uppercase">Rate/Tab</span>
                                            </td>
                                            <td className="px-6 py-3 font-bold text-sm text-slate-900">
                                                <div className="flex flex-col">
                                                    <span>₹{s.mrp} <span className="text-[8px] text-slate-400 uppercase">/Strip</span></span>
                                                    <span className="text-[10px] text-slate-400 font-normal">₹{(s.mrp / (s.tablets_per_strip || 1)).toFixed(2)} /Tab</span>
                                                </div>
                                            </td>
                                            <td className="px-6 py-3">
                                                <ActionTooltip text="View Details"><button onClick={() => setSelectedStockItem(s)} className="p-1.5 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all"><Eye size={16} /></button></ActionTooltip>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                        <div className="p-3 border-t border-slate-100 bg-slate-50/50 flex justify-between items-center shrink-0">
                            <div className="flex items-center gap-2"><span className="text-xs font-bold text-slate-500">Rows:</span><select className="bg-white border border-slate-200 text-slate-700 text-xs rounded-lg p-1 outline-none font-bold" value={rowsPerPage} onChange={(e) => { setRowsPerPage(e.target.value); setPage(1); }}><option value={10}>10</option><option value={50}>50</option><option value="all">All</option></select></div>
                            <Pagination current={page} total={Math.ceil(stockData.count / (rowsPerPage === 'all' ? stockData.count || 1 : rowsPerPage))} onPageChange={setPage} loading={loading} compact />
                        </div>
                    </>
                )}

                {/* 2. POS TAB */}
                {activeTab === 'pos' && (
                    <div className="flex h-full divide-x divide-slate-100">
                        <div className="w-[65%] flex flex-col bg-[#F8FAFC]">
                            {/* ... (POS Left Side - Same as fixed previously) ... */}
                            <div className="flex h-1/3 border-b border-slate-200">
                                <div className="w-1/3 border-r border-slate-100 bg-white flex flex-col">
                                    <div className="p-3 border-b border-slate-100 bg-slate-50/50"><h3 className="font-black text-slate-600 uppercase tracking-wider text-[10px] flex items-center gap-2"><Clock size={12} /> Pending Rx Queue</h3></div>
                                    <div className="flex-1 overflow-y-auto p-2 space-y-2">
                                        {(Array.isArray(pendingVisits) ? pendingVisits : []).length === 0 ? (<div className="h-full flex items-center justify-center text-slate-300 text-xs font-bold uppercase">No Pending Rx</div>) : (
                                            pendingVisits.map(v => (
                                                <div key={v.id} onClick={() => loadPrescription(v)} className="p-3 bg-white border border-slate-100 rounded-lg cursor-pointer hover:border-blue-400 hover:shadow-md transition-all group">
                                                    <div className="flex justify-between items-start"><h4 className="font-bold text-xs text-slate-900 line-clamp-1">{v.patient_name}</h4><span className="text-[8px] font-black bg-blue-50 text-blue-600 px-1 py-0.5 rounded uppercase">New</span></div>
                                                    <p className="text-[9px] text-slate-400 truncate mt-1">Dr. {v.doctor_name || 'Ref'}</p>
                                                </div>
                                            ))
                                        )}
                                    </div>
                                </div>
                                <div className="flex-1 p-6 bg-white space-y-4">
                                    <div className="grid grid-cols-2 gap-4">
                                        <div className="space-y-1 relative"><label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Patient</label><div className="relative group"><User className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} /><input className="w-full pl-9 pr-8 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold focus:bg-white focus:border-blue-500 outline-none transition-all" placeholder="Search Patient..." value={selectedPatient ? selectedPatient.full_name : patientSearch} onChange={e => { setSelectedPatient(null); searchPatients(e.target.value); }} />{selectedPatient && <X className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 cursor-pointer hover:text-red-500" size={14} onClick={() => { setSelectedPatient(null); setPatientSearch(''); }} />}{patients.length > 0 && !selectedPatient && (<div className="absolute top-full left-0 right-0 mt-1 bg-white border border-slate-100 rounded-xl shadow-xl z-20 overflow-hidden max-h-40 overflow-y-auto">{patients.map(p => (<div key={p.p_id} onClick={() => { setSelectedPatient(p); setPatients([]); setPatientSearch(''); }} className="px-4 py-2 hover:bg-slate-50 cursor-pointer text-xs font-bold text-slate-700 border-b border-slate-50 last:border-0">{p.full_name} <span className="text-slate-400 font-normal">({p.phone})</span></div>))}</div>)}</div></div>
                                        <div className="space-y-1 relative"><label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Doctor</label><div className="relative group"><Activity className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} /><input className="w-full pl-9 pr-8 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold focus:bg-white focus:border-blue-500 outline-none transition-all" placeholder="Assign Doctor..." value={selectedDoctor ? selectedDoctor.username : doctorSearch} onChange={e => { setSelectedDoctor(null); searchDoctors(e.target.value); }} />{selectedDoctor && <X className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 cursor-pointer hover:text-red-500" size={14} onClick={() => { setSelectedDoctor(null); setDoctorSearch(''); }} />}{doctors.length > 0 && !selectedDoctor && (<div className="absolute top-full left-0 right-0 mt-1 bg-white border border-slate-100 rounded-xl shadow-xl z-20 overflow-hidden max-h-40 overflow-y-auto">{doctors.map(d => (<div key={d.u_id} onClick={() => { setSelectedDoctor(d); setDoctors([]); setDoctorSearch(''); }} className="px-4 py-2 hover:bg-slate-50 cursor-pointer text-xs font-bold text-slate-700 border-b border-slate-50 last:border-0">Dr. {d.username}</div>))}</div>)}</div></div>
                                    </div>
                                </div>
                            </div>
                            <div className="flex-1 flex flex-col overflow-hidden p-6">
                                <div className="relative mb-6 shrink-0"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={20} /><input className="w-full pl-12 pr-44 py-4 bg-white border-2 border-blue-100 rounded-2xl text-lg font-medium text-slate-900 placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10 transition-all outline-none shadow-sm" placeholder="Scan barcode or type medicine name..." value={medSearch} onChange={e => searchMeds(e.target.value)} autoFocus /><div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-2"><span className="text-[10px] font-black text-slate-400 uppercase tracking-widest hidden xl:block">GST Reduction</span><select className="px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-bold text-slate-700 outline-none focus:border-blue-500" value={gstRate} onChange={(e) => setGstRate(Number(e.target.value))}>{[0, 5, 12, 18, 28].map(r => <option key={r} value={r}>{r === 0 ? '0% (None)' : `${r}% GST`}</option>)}</select></div></div>
                                <div className="flex-1 overflow-y-auto">
                                    {medResults.length > 0 ? (
                                        <div className="grid grid-cols-2 lg:grid-cols-3 gap-4 pb-20">
                                            {medResults.map(m => (
                                                <div key={m.med_id} onClick={() => addToCart(m)} className="bg-white p-4 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md hover:border-blue-200 cursor-pointer transition-all group flex flex-col justify-between h-32">
                                                    <div className="flex justify-between items-start"><div><h4 className="font-bold text-slate-900 line-clamp-1 text-sm">{m.name}</h4><p className="text-[10px] font-bold text-slate-400 uppercase mt-1">{m.manufacturer}</p></div><div className="w-6 h-6 rounded-lg bg-slate-50 text-slate-400 flex items-center justify-center group-hover:bg-blue-600 group-hover:text-white transition-colors"><Plus size={14} /></div></div>
                                                    <div className="flex justify-between items-end">
                                                        <div className="flex flex-col">
                                                            <div className={`text-[10px] font-bold px-2 py-0.5 rounded-md ${m.qty_available < 10 ? 'bg-red-50 text-red-600' : 'bg-emerald-50 text-emerald-600'}`}>
                                                                Stock: {m.qty_available} Tab
                                                            </div>
                                                            <span className="text-[8px] font-bold text-slate-400 mt-1 uppercase">({Math.floor(m.qty_available / (m.tablets_per_strip || 1))} STR + {m.qty_available % (m.tablets_per_strip || 1)} TAB)</span>
                                                        </div>
                                                        <p className="text-lg font-black text-slate-900 text-right">
                                                            ₹{(m.mrp / (m.tablets_per_strip || 1)).toFixed(2)}
                                                            <span className="block text-[9px] text-slate-400 font-bold uppercase">Rate / Tablet</span>
                                                            <span className="block text-[8px] text-slate-300 line-through">MRP: ₹{(m.mrp / (m.tablets_per_strip || 1)).toFixed(2)}</span>
                                                        </p>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    ) : (<div className="h-full flex flex-col items-center justify-center text-slate-300"><Search size={48} className="mb-4 opacity-50" /><p className="font-bold text-sm">Start typing to search inventory...</p></div>)}
                                </div>
                            </div>
                        </div>
                        {/* POS Right Side */}
                        <div className="w-[35%] bg-white flex flex-col shadow-[-10px_0_40px_-15px_rgba(0,0,0,0.05)] z-20">
                            <div className="p-6 border-b border-slate-100 bg-slate-50 shrink-0"><div className="flex justify-between items-center mb-4"><h2 className="text-sm font-black text-slate-900 uppercase tracking-widest flex items-center gap-2"><ShoppingCart size={16} className="text-blue-600" /> Current Bill</h2><span className="text-xs font-bold text-slate-400">{new Date().toLocaleDateString()}</span></div>{selectedPatient ? (<div className="p-3 bg-white border border-slate-200 rounded-xl flex items-center justify-between"><div><p className="text-[10px] text-slate-400 font-bold uppercase">Billed To</p><p className="text-sm font-bold text-slate-900">{selectedPatient.full_name}</p></div><button onClick={() => setSelectedPatient(null)} className="text-slate-400 hover:text-red-500"><X size={16} /></button></div>) : <div className="p-3 bg-yellow-50 border border-yellow-100 rounded-xl text-xs font-bold text-yellow-700 text-center">Walk-In Customer (No Name)</div>}</div>
                            <div className="flex-1 overflow-y-auto p-4 space-y-3 bg-white">
                                {cart.length === 0 ? (<div className="flex flex-col items-center justify-center h-full opacity-40"><ShoppingCart size={40} className="mb-2" /><p className="text-xs font-bold uppercase">Empty Cart</p></div>) : cart.map((item, idx) => (
                                    <div key={idx} className="flex justify-between items-center p-3 border-b border-slate-50 last:border-0 hover:bg-slate-50 transition-colors">
                                        <div className="flex-1">
                                            <p className="text-sm font-bold text-slate-900 line-clamp-1">{item.name}</p>
                                            <p className="text-[10px] text-slate-400 font-mono">₹{item.selling_price.toFixed(2)} / Tab x {item.qty} Tabs</p>
                                        </div>
                                        <div className="flex items-center gap-3">
                                            <div className="flex items-center gap-1 bg-slate-100 rounded-lg p-1">
                                                <button onClick={() => setCart(cart.map((c, i) => i === idx ? { ...c, qty: Math.max(1, c.qty - 1) } : c))} className="w-5 h-5 flex items-center justify-center text-slate-600 hover:bg-white rounded transition-colors">-</button>
                                                <span className="text-[10px] font-black w-6 text-center">{item.qty}</span>
                                                <button onClick={() => {
                                                    if (item.qty < item.qty_available) setCart(cart.map((c, i) => i === idx ? { ...c, qty: c.qty + 1 } : c));
                                                    else showToast('error', 'OOS');
                                                }} className="w-5 h-5 flex items-center justify-center text-slate-600 hover:bg-white rounded transition-colors">+</button>
                                            </div>
                                            <p className="text-sm font-black text-slate-900">₹{(item.selling_price * item.qty).toFixed(2)}</p>
                                            <button onClick={() => { const newCart = cart.filter((_, i) => i !== idx); setCart(newCart); }} className="text-slate-300 hover:text-red-500 transition-colors"><Trash2 size={14} /></button>
                                        </div>
                                    </div>
                                ))}
                            </div>
                            <div className="p-6 bg-slate-50 border-t border-slate-100 space-y-4 shrink-0">
                                <div className="space-y-2"><div className="border-t border-dashed border-slate-300 pt-2 flex justify-between items-end"><span className="text-xs font-black text-slate-900 uppercase tracking-wider">Net Payable</span><span className="text-3xl font-black text-slate-900 leading-none">₹{calculateTotals().net.toFixed(2)}</span></div></div>
                                <button onClick={handleCheckout} disabled={cart.length === 0} className="w-full py-4 bg-emerald-600 hover:bg-emerald-700 disabled:bg-slate-200 disabled:text-slate-400 text-white rounded-2xl font-bold shadow-lg shadow-emerald-900/10 transition-all active:scale-[0.98] flex items-center justify-center gap-2 uppercase tracking-widest text-xs"><Send size={16} /> Dispense & Send to Billing</button>
                            </div>
                        </div>
                    </div>
                )}

                {/* 3. PURCHASES TAB - FIXED LAYOUT (40/60 Split & Scrolling) */}
                {activeTab === 'purchases' && (
                    <div className="flex h-full divide-x divide-slate-100">

                        {/* LEFT COLUMN: Upload & Manual Entry (40%) */}
                        <div className="w-[40%] flex flex-col h-full bg-slate-50 overflow-y-auto">
                            <div className="p-8 space-y-8">
                                {/* Manual Entry Card */}
                                <div className="bg-white p-8 rounded-[2.5rem] shadow-xl shadow-blue-900/5 border border-slate-100 text-center relative overflow-hidden group">
                                    <div className="absolute top-0 right-0 w-32 h-32 bg-blue-50 rounded-full -mr-16 -mt-16 transition-transform group-hover:scale-110" />
                                    <div className="relative z-10">
                                        <div className="w-16 h-16 bg-blue-600 text-white rounded-3xl flex items-center justify-center mx-auto mb-4 shadow-lg shadow-blue-500/20"><PackagePlus size={32} /></div>
                                        <h3 className="text-xl font-black text-slate-900 mb-2">Manual Entry</h3>
                                        <p className="text-xs text-slate-500 font-bold mb-6 uppercase tracking-wider">Add Stock via Barcode / Form</p>
                                        <Button onClick={() => setShowManualPurchaseModal(true)} className="w-full bg-blue-600 hover:bg-blue-700 h-12 rounded-xl text-xs font-black uppercase tracking-widest shadow-xl shadow-blue-500/10">Open Entry Form</Button>
                                    </div>
                                </div>

                                {/* CSV Import Card */}
                                <div className="bg-white p-8 rounded-[2.5rem] shadow-xl shadow-slate-200/50 border border-slate-100 text-center relative">
                                    <div className="w-16 h-16 bg-slate-900 text-white rounded-3xl flex items-center justify-center mx-auto mb-4 shadow-lg"><FileSpreadsheet size={32} /></div>
                                    <h2 className="text-xl font-black text-slate-900 mb-2">Bulk Import</h2>
                                    <p className="text-xs text-slate-500 font-bold mb-6 uppercase tracking-wider">Upload Supplier Invoice CSV</p>

                                    <div className="space-y-4">
                                        <div className="relative text-left">
                                            <div className="flex justify-between items-end mb-1"><label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">1. Supplier</label><button onClick={() => setShowAddSupplierModal(true)} className="text-[10px] font-bold text-blue-600 hover:underline flex items-center gap-1 uppercase tracking-wider"><Plus size={10} /> Add New</button></div>
                                            <select className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold outline-none focus:border-blue-500 transition-colors" value={selectedSupplier} onChange={(e) => setSelectedSupplier(e.target.value)}><option value="">Select Supplier...</option>{suppliers.map(s => <option key={s.id} value={s.supplier_name}>{s.supplier_name}</option>)}</select>
                                        </div>
                                        <div className="relative text-left">
                                            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1 mb-1 block">2. CSV File</label>
                                            <label className={`flex flex-col items-center justify-center h-28 border-2 border-dashed rounded-2xl cursor-pointer transition-all ${fileToUpload ? 'border-emerald-500 bg-emerald-50' : 'border-slate-200 hover:border-blue-400 hover:bg-white'}`}>
                                                <input type="file" className="hidden" accept=".csv" onChange={handleFileChange} disabled={!selectedSupplier} />
                                                {fileToUpload ? (<div className="text-center"><FileText size={24} className="text-emerald-600 mx-auto mb-2" /><p className="text-xs font-bold text-emerald-800 break-all px-4">{fileToUpload.name}</p></div>) : (<div className="text-center text-slate-400"><Plus size={24} className="mx-auto mb-2" /><p className="text-[10px] font-bold uppercase tracking-wider">Click to Browse</p></div>)}
                                            </label>
                                        </div>
                                        <button onClick={handleConfirmUpload} disabled={!fileToUpload || uploadLoading} className="w-full py-4 bg-slate-900 text-white rounded-xl font-bold shadow-lg shadow-slate-900/20 hover:bg-slate-800 disabled:bg-slate-200 disabled:text-slate-400 transition-all text-xs uppercase tracking-widest">{uploadLoading ? 'Processing...' : 'Confirm Upload'}</button>
                                    </div>
                                </div>

                                {uploadResult && (<div className={`p-4 rounded-2xl border-2 text-sm font-bold flex items-start gap-3 shadow-sm ${uploadResult.success ? 'bg-emerald-50 border-emerald-100 text-emerald-700' : 'bg-rose-50 border-rose-100 text-rose-700'}`}><div className="mt-0.5">{uploadResult.success ? <CheckCircle2 size={18} /> : <AlertTriangle size={18} />}</div><div><p className="uppercase tracking-wide text-xs mb-1">{uploadResult.message}</p><p className="opacity-80 font-normal">{uploadResult.details}</p></div></div>)}
                            </div>
                        </div>

                        {/* RIGHT COLUMN: HISTORY (60%) */}
                        <div className="w-[60%] flex flex-col bg-white h-full">
                            <div className="p-6 border-b border-slate-100 flex justify-between items-center"><h3 className="font-bold text-slate-900 flex items-center gap-2"><Clock size={18} className="text-slate-400" /> Recent Imports</h3></div>
                            <div className="flex-1 overflow-auto">
                                <table className="w-full text-left border-collapse">
                                    <thead className="bg-slate-50 sticky top-0 shadow-sm"><tr>{['Invoice', 'Supplier', 'Date', 'Items', 'Action'].map(h => <th key={h} className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">{h}</th>)}</tr></thead>
                                    <tbody className="divide-y divide-slate-50 font-medium text-sm text-slate-600">
                                        {recentImports.map(imp => (
                                            <tr key={imp.id} className="hover:bg-slate-50 transition-colors">
                                                <td className="px-6 py-4 font-bold text-slate-900">#{imp.invoice_no}</td>
                                                <td className="px-6 py-4">{suppliers.find(s => s.id === imp.supplier)?.supplier_name || imp.supplier_name || 'N/A'}</td>
                                                <td className="px-6 py-4 font-mono text-xs text-slate-500">{new Date(imp.created_at).toLocaleDateString()}</td>
                                                <td className="px-6 py-4"><span className="inline-flex items-center px-2.5 py-1 rounded-md bg-slate-100 text-slate-600 text-xs font-bold">{imp.items_detail ? imp.items_detail.length : 0}</span></td>
                                                <td className="px-6 py-4"><ActionTooltip text="View Details"><button onClick={() => setSelectedImport(imp)} className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all"><Eye size={18} /></button></ActionTooltip></td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                )}
            </div>

            {/* --- Modals (Stock Details, Print, Import Details, Add Supplier) --- */}
            <AnimatePresence>
                {selectedStockItem && (
                    <div className="fixed inset-0 z-50 flex items-center justify-center p-6 no-print">
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="absolute inset-0 bg-slate-900/40 backdrop-blur-sm" onClick={() => setSelectedStockItem(null)} />
                        <motion.div initial={{ scale: 0.9, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.9, y: 20 }} className="bg-white w-full max-w-md rounded-[2rem] shadow-2xl relative z-10 p-8">
                            <div className="flex justify-between items-start mb-6"><div><h2 className="text-xl font-black text-slate-900">{selectedStockItem.name}</h2><p className="text-xs font-bold text-slate-400 uppercase tracking-widest mt-1">{selectedStockItem.manufacturer}</p></div><button onClick={() => setSelectedStockItem(null)} className="p-2 bg-slate-50 rounded-full hover:bg-slate-100"><X size={18} /></button></div>
                            <div className="space-y-4">
                                <div className="p-4 bg-slate-50 rounded-xl border border-slate-100 flex justify-between items-center">
                                    <span className="text-xs font-bold text-slate-500 uppercase">Stock Available</span>
                                    <div className="text-right">
                                        <span className="text-xl font-black text-emerald-600">{selectedStockItem.qty_available} Tab</span>
                                        <p className="text-[10px] font-bold text-slate-400 uppercase">{Math.floor(selectedStockItem.qty_available / (selectedStockItem.tablets_per_strip || 1))} Strips + {selectedStockItem.qty_available % (selectedStockItem.tablets_per_strip || 1)} Tab</p>
                                    </div>
                                </div>
                                <div className="grid grid-cols-2 gap-4">
                                    <div className="p-4 bg-white border border-slate-100 rounded-xl"><p className="text-[10px] font-bold text-slate-400 uppercase">Batch No</p><p className="font-mono font-bold text-slate-900">{selectedStockItem.batch_no}</p></div>
                                    <div className="p-4 bg-white border border-slate-100 rounded-xl"><p className="text-[10px] font-bold text-slate-400 uppercase">Tablets/Strip</p><p className="font-mono font-bold text-slate-900">{selectedStockItem.tablets_per_strip || 1}</p></div>
                                </div>
                                <div className="p-4 bg-white border border-slate-100 rounded-xl"><p className="text-[10px] font-bold text-slate-400 uppercase">Expiry</p><p className="font-mono font-bold text-slate-900">{new Date(selectedStockItem.expiry_date).toLocaleDateString()}</p></div>
                                {selectedStockItem.tablets_per_strip > 1 && (
                                    <button onClick={() => handleSyncToTablets(selectedStockItem)} className="w-full mt-4 h-12 bg-blue-50 text-blue-600 rounded-2xl font-black text-[10px] uppercase tracking-widest hover:bg-blue-100 transition-all border border-blue-200">
                                        Convert Strips to Tablets (x{selectedStockItem.tablets_per_strip})
                                    </button>
                                )}
                            </div>
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>

            <AnimatePresence>
                {showPrintModal && lastSale && (
                    <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 no-print">
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="absolute inset-0 bg-slate-900/60 backdrop-blur-md" />
                        <motion.div initial={{ scale: 0.95 }} animate={{ scale: 1 }} exit={{ scale: 0.95 }} className="bg-white w-full max-w-lg rounded-3xl shadow-2xl relative z-10 overflow-hidden flex flex-col max-h-[90vh]">
                            <div className="p-4 bg-slate-900 text-white flex justify-between items-center shrink-0"><h3 className="font-bold text-sm ml-2">Print Receipt</h3><div className="flex gap-2"><button onClick={() => window.print()} className="p-2 bg-blue-600 rounded-lg hover:bg-blue-500"><Printer size={18} /></button><button onClick={() => setShowPrintModal(false)} className="p-2 bg-slate-800 rounded-lg hover:bg-slate-700"><X size={18} /></button></div></div>
                            <div className="flex-1 overflow-y-auto bg-white" id="printable-area"><ReceiptTemplate sale={lastSale} /></div>
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>

            <AnimatePresence>
                {selectedImport && (
                    <div className="fixed inset-0 z-50 flex items-center justify-center p-6 no-print">
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="absolute inset-0 bg-slate-900/40 backdrop-blur-sm" onClick={() => setSelectedImport(null)} />
                        <motion.div initial={{ scale: 0.9, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.9, y: 20 }} className="bg-white w-full max-w-4xl rounded-[2rem] shadow-2xl relative z-10 overflow-hidden flex flex-col max-h-[85vh]">
                            <div className="p-8 bg-slate-50 border-b border-slate-100">
                                <div className="flex justify-between items-center mb-6"><div><h2 className="text-2xl font-black text-slate-900">Invoice #{selectedImport.invoice_no || '---'}</h2><p className="text-sm font-bold text-slate-400">Imported on {new Date(selectedImport.created_at).toLocaleDateString()}</p></div><button onClick={() => setSelectedImport(null)} className="p-2 bg-white rounded-full hover:text-red-500 shadow-sm"><X size={20} /></button></div>
                                <div className="grid grid-cols-3 gap-4">
                                    <div className="p-4 bg-white rounded-xl border border-slate-200 shadow-sm"><p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Total Value</p><p className="text-2xl font-black text-slate-900">₹{selectedImport.total_amount}</p></div>
                                    <div className="p-4 bg-white rounded-xl border border-slate-200 shadow-sm"><p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Items Count</p><p className="text-2xl font-black text-emerald-600">{selectedImport.items_detail?.length || 0}</p></div>
                                    <div className="p-4 bg-white rounded-xl border border-slate-200 shadow-sm"><p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Status</p><div className="flex items-center gap-2 mt-1"><CheckCircle2 size={20} className="text-blue-500" /><span className="text-lg font-bold text-slate-700">Verified</span></div></div>
                                </div>
                            </div>
                            <div className="flex-1 overflow-auto p-0">
                                <table className="w-full text-left border-collapse">
                                    <thead className="bg-white sticky top-0 shadow-sm"><tr>{['Product', 'Batch', 'Exp', 'Qty', 'MRP', 'PTR', 'Amount'].map(h => <th key={h} className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest border-b border-slate-50">{h}</th>)}</tr></thead>
                                    <tbody className="divide-y divide-slate-50">{selectedImport.items_detail?.map((item, idx) => (
                                        <tr key={idx} className="hover:bg-slate-50 transition-colors"><td className="px-6 py-3 font-bold text-sm text-slate-900">{item.product_name}</td><td className="px-6 py-3 font-mono text-xs text-slate-600">{item.batch_no}</td><td className="px-6 py-3 font-mono text-xs text-slate-600">{item.expiry_date}</td><td className="px-6 py-3 font-bold text-emerald-600">{item.qty} {item.free_qty > 0 && <span className="text-xs text-emerald-400">+ {item.free_qty} Free</span>}</td><td className="px-6 py-3 text-sm text-slate-600">₹{item.mrp}</td><td className="px-6 py-3 text-sm text-slate-600">₹{item.ptr}</td><td className="px-6 py-3 font-black text-slate-900">₹{((item.ptr || 0) * item.qty).toFixed(2)}</td></tr>
                                    ))}</tbody>
                                </table>
                            </div>
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>

            <AnimatePresence>
                {showAddSupplierModal && (
                    <div className="fixed inset-0 z-[60] flex items-center justify-center p-6 bg-slate-950/40 backdrop-blur-sm no-print">
                        <motion.div initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.9, opacity: 0 }} className="bg-white w-full max-w-sm rounded-[2rem] shadow-2xl overflow-hidden p-8 space-y-6">
                            <div className="flex justify-between items-center"><h3 className="font-black text-xl text-slate-900 uppercase tracking-wide">New Supplier</h3><X className="cursor-pointer text-slate-400 hover:text-rose-500" onClick={() => setShowAddSupplierModal(false)} /></div>
                            <form onSubmit={handleAddSupplier} className="space-y-4"><Input placeholder="Supplier Name" value={newSupplierName} onChange={e => setNewSupplierName(e.target.value)} required className="bg-slate-50 border-2 border-slate-100 rounded-xl font-bold" /><Button type="submit" className="w-full h-12 rounded-xl font-black uppercase tracking-widest text-sm shadow-xl shadow-sky-500/20">Create Supplier</Button></form>
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>

            {/* Manual Purchase Modal - PREMIUM UPGRADE */}
            <AnimatePresence>
                {showManualPurchaseModal && (
                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
                        <motion.div initial={{ scale: 0.95, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.95, y: 20 }} className="bg-white rounded-[32px] shadow-2xl w-full max-w-6xl max-h-[90vh] flex flex-col overflow-hidden border border-slate-100">
                            <div className="p-6 border-b border-slate-100 flex justify-between items-center shrink-0 bg-slate-50/50">
                                <div className="flex items-center gap-3">
                                    <div className="w-10 h-10 bg-blue-600 rounded-2xl flex items-center justify-center text-white shadow-lg shadow-blue-500/20"><Plus size={20} rotation={45} /></div>
                                    <div><h2 className="text-xl font-black text-slate-900 tracking-tight">Manual Stock-In</h2><p className="text-xs font-bold text-slate-400 uppercase tracking-widest">Create New Purchase Invoice</p></div>
                                </div>
                                <button onClick={() => setShowManualPurchaseModal(false)} className="p-2 hover:bg-slate-100 rounded-xl transition-colors"><X size={20} /></button>
                            </div>
                            <div className="p-8 overflow-y-auto space-y-8">
                                <div className="grid grid-cols-4 gap-6">
                                    <div className="space-y-1">
                                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Supplier</label>
                                        <select className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-2.5 text-xs font-bold focus:bg-white focus:ring-2 focus:ring-blue-500/20 outline-none transition-all" value={manualInvoice.supplier} onChange={(e) => setManualInvoice(prev => ({ ...prev, supplier: e.target.value }))}><option value="">Select Supplier...</option>{(Array.isArray(suppliers) ? suppliers : []).map(s => <option key={s.id} value={s.id}>{s.supplier_name}</option>)}</select>
                                    </div>
                                    <Input label="Invoice Number" placeholder="e.g. INV-001" value={manualInvoice.supplier_invoice_no} onChange={(e) => setManualInvoice(prev => ({ ...prev, supplier_invoice_no: e.target.value }))} />
                                    <Input label="Invoice Date" type="date" value={manualInvoice.invoice_date} onChange={(e) => setManualInvoice(prev => ({ ...prev, invoice_date: e.target.value }))} />
                                    <div className="space-y-1"><label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Type</label><select className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-2.5 text-xs font-bold focus:bg-white focus:ring-2 focus:ring-blue-500/20 outline-none transition-all" value={manualInvoice.purchase_type} onChange={(e) => setManualInvoice(prev => ({ ...prev, purchase_type: e.target.value }))}><option value="CASH">CASH</option><option value="CREDIT">CREDIT</option></select></div>
                                </div>
                                <div className="bg-slate-900 rounded-2xl p-6 flex items-center justify-between border-b-4 border-blue-600 shadow-xl">
                                    <div className="flex items-center gap-4"><div className="w-12 h-12 bg-blue-600/10 text-blue-400 rounded-xl flex items-center justify-center border border-blue-400/20"><Search size={24} /></div><div><h3 className="text-white font-bold">Quick Barcode Scanning</h3><p className="text-slate-400 text-xs">Scan any product to add it instantly to the table below.</p></div></div>
                                    <div className="w-96 relative"><Input placeholder="Scan Barcode Now..." className="bg-white/5 border-white/10 text-white placeholder:text-slate-600 h-14 pr-12 text-lg font-mono tracking-widest focus:bg-white/10 transition-all" value={scannedBarcode} onChange={(e) => setScannedBarcode(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') handleBarcodeStockIn(e.target.value); }} autoFocus /><div className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-600"><CheckCircle2 size={24} /></div></div>
                                </div>
                                <div className="border border-slate-200 rounded-[24px] overflow-hidden shadow-sm">
                                    <table className="w-full text-left">
                                        <thead className="bg-slate-50 border-b border-slate-100">
                                            <tr className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
                                                <th className="px-4 py-4 w-[20%]">Product Name</th><th className="px-4 py-4">Batch</th><th className="px-4 py-4">TPS</th><th className="px-4 py-4">Qty(Str)</th><th className="px-4 py-4">Free</th><th className="px-4 py-4 bg-blue-50/50">Total(Tab)</th><th className="px-4 py-4 text-right">Total Buy</th><th className="px-4 py-4 text-right">Total MRP</th><th className="px-4 py-4 text-right bg-blue-50/50">MRP (Tab)</th><th className="px-4 py-4 text-center">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody className="divide-y divide-slate-50">
                                            {manualInvoice.items.map((item, idx) => (
                                                <tr key={idx} className="group hover:bg-slate-50/50">
                                                    <td className="px-4 py-3"><input className="w-full bg-transparent border-none text-xs font-bold text-slate-900 outline-none p-0" placeholder="Med name..." value={item.product_name} onChange={(e) => handleManualItemChange(idx, 'product_name', e.target.value)} /></td>
                                                    <td className="px-4 py-3">
                                                        <div className="flex flex-col gap-1">
                                                            <input className="w-full bg-transparent border-none text-xs font-mono text-slate-600 outline-none p-0" placeholder="BATCH" value={item.batch_no} onChange={(e) => handleManualItemChange(idx, 'batch_no', e.target.value)} />
                                                            <input className="w-full bg-transparent border-none text-[10px] text-slate-400 outline-none p-0" type="date" value={item.expiry_date} onChange={(e) => handleManualItemChange(idx, 'expiry_date', e.target.value)} />
                                                        </div>
                                                    </td>
                                                    <td className="px-4 py-3 w-16 text-center"><input className="w-full bg-transparent border-none text-xs font-bold text-center outline-none p-0" type="number" value={item.tablets_per_strip} onChange={(e) => handleManualItemChange(idx, 'tablets_per_strip', parseInt(e.target.value) || 1)} /></td>
                                                    <td className="px-4 py-3 w-16 text-center"><input className="w-full bg-transparent border-none text-xs font-bold text-center outline-none p-0" type="number" value={item.qty} onChange={(e) => handleManualItemChange(idx, 'qty', e.target.value)} /></td>
                                                    <td className="px-4 py-3 w-12 text-center"><input className="w-full bg-transparent border-none text-xs font-bold text-center outline-none p-0" type="number" value={item.free_qty} onChange={(e) => handleManualItemChange(idx, 'free_qty', e.target.value)} /></td>
                                                    <td className="px-4 py-3 text-center bg-blue-50/30 text-xs font-black text-blue-600">{((parseInt(item.qty) || 0) + (parseInt(item.free_qty) || 0)) * (parseInt(item.tablets_per_strip) || 1)}</td>
                                                    <td className="px-4 py-3 w-20 text-right">
                                                        <div className="flex items-center justify-end font-bold text-slate-900 text-xs">₹<input className="w-14 bg-transparent border-none text-right outline-none p-0" type="number" value={item.purchase_rate} onChange={(e) => handleManualItemChange(idx, 'purchase_rate', e.target.value)} /></div>
                                                        <span className="text-[9px] text-slate-400 block">@₹{((parseFloat(item.purchase_rate) || 0) / (parseInt(item.qty) || 1)).toFixed(2)}</span>
                                                    </td>
                                                    <td className="px-4 py-3 w-20 text-right">
                                                        <div className="flex items-center justify-end font-bold text-slate-900 text-xs">₹<input className="w-14 bg-transparent border-none text-right outline-none p-0" type="number" value={item.mrp} onChange={(e) => handleManualItemChange(idx, 'mrp', e.target.value)} /></div>
                                                        <span className="text-[9px] text-slate-400 block">@₹{((parseFloat(item.mrp) || 0) / (parseInt(item.qty) || 1)).toFixed(2)}</span>
                                                    </td>
                                                    <td className="px-4 py-3 text-right bg-blue-50/30 text-[10px] font-bold text-blue-600">₹{(((parseFloat(item.mrp) || 0) / (parseInt(item.qty) || 1)) / (parseInt(item.tablets_per_strip) || 1)).toFixed(2)}</td>
                                                    <td className="px-4 py-3 text-center"><button onClick={() => removeManualItem(idx)} className="p-1.5 text-slate-300 hover:text-red-500 hover:bg-red-50 rounded-lg transition-all"><Trash2 size={16} /></button></td>
                                                </tr>
                                            ))}
                                            {manualInvoice.items.length === 0 && (<tr><td colSpan="8" className="p-12 text-center text-slate-400 font-bold text-xs uppercase tracking-widest bg-slate-50/50">Scan or add items to begin</td></tr>)}
                                        </tbody>
                                        <tfoot className="bg-slate-50 font-bold">
                                            <tr className="text-slate-900 text-xs">
                                                <td colSpan="6" className="px-4 py-4">Total Items: {manualInvoice.items.length} | Total Tablets: {manualInvoice.items.reduce((acc, item) => acc + (((parseInt(item.qty) || 0) + (parseInt(item.free_qty) || 0)) * (parseInt(item.tablets_per_strip) || 1)), 0)}</td>
                                                <td colSpan="4" className="px-4 py-4 text-right">Invoice Value: ₹{manualInvoice.items.reduce((acc, item) => acc + (parseFloat(item.purchase_rate) || 0), 0).toFixed(2)}</td>
                                                <td className="px-4 py-3 text-center"><button onClick={() => setManualInvoice(prev => ({ ...prev, items: [...prev.items, { product_name: '', barcode: '', batch_no: '', expiry_date: '', qty: 1, free_qty: 0, purchase_rate: 0, ptr: 0, mrp: 0, manufacturer: '', hsn: '', tablets_per_strip: 10 }] }))} className="p-2 bg-white border border-slate-200 text-blue-600 rounded-xl hover:shadow-md transition-all shadow-sm"><Plus size={20} /></button></td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <div className="p-6 border-t border-slate-100 bg-slate-50/50 flex justify-end gap-3 shrink-0">
                                <Button variant="outline" onClick={() => setShowManualPurchaseModal(false)}>Cancel</Button>
                                <Button className="bg-blue-600 hover:bg-blue-700 px-8" onClick={submitManualPurchase} loading={loading}>Save & Stock-In</Button>
                            </div>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>

        </div>
    );
};

export default Pharmacy;