# Generated by Django 6.0.1 on 2026-01-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_initial'),
        ('patients', '0003_alter_patient_age_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornote',
            name='prescription',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='doctornote',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_note', to='patients.visit'),
        ),
    ]
