# Generated by Django 5.2.3 on 2026-01-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_alter_doctornote_prescription_alter_doctornote_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornote',
            name='lab_referral_details',
            field=models.TextField(blank=True),
        ),
    ]
