# Generated by Django 5.2.4 on 2026-01-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_doctornote_lab_referral_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CasualtyLog',
        ),
    ]
