# Generated by Django 6.0.1 on 2026-01-08 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='labinventory',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='labinventory',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
