# Generated by Django 5.2.4 on 2026-01-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_labcharge_amount_alter_labinventory_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcharge',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
