# Generated by Django 5.2.4 on 2026-01-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_labcharge_report_date_labcharge_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcharge',
            name='specimen',
            field=models.CharField(blank=True, default='BLOOD', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labcharge',
            name='technician_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
