# Generated by Django 5.2.4 on 2026-01-15 05:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_labcharge_specimen_alter_labcharge_technician_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabInventoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out')], max_length=20)),
                ('qty', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('performed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lab.labinventory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
