# Generated by Django 5.2.4 on 2026-01-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_labinventorylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinventory',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
