# Generated by Django 5.2.4 on 2026-01-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_alter_labinventory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinventory',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
