# Generated by Django 5.2.4 on 2026-01-15 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_labinventory_cost_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('HAEMATOLOGY', 'Haematology'), ('IMMUNO_HAEMATOLOGY', 'Immuno Haematology'), ('BIOCHEMISTRY', 'Biochemistry'), ('URINE', 'Urine Test'), ('STOOL', 'Stool Test'), ('MICROBIOLOGY', 'Microbiology'), ('SEROLOGY', 'Serology'), ('HORMONE', 'Hormone Assay'), ('XRAY', 'X-Ray'), ('OTHERS', 'Others')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('normal_range', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
