# Generated by Django 5.2.3 on 2026-01-17 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_labtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('normal_range', models.TextField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lab.labtest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
