# Generated by Django 5.2.4 on 2026-01-21 11:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_labtestparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRequiredItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('qty_per_test', models.PositiveIntegerField(default=1)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labinventory')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_items', to='lab.labtest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
