# Generated by Django 5.2.4 on 2026-01-22 06:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_labtestrequireditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='labtest',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
