# Generated by Django 5.2.4 on 2026-01-23 06:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_labcategory_alter_labtest_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('gst_no', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='labinventory',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='labinventory',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='labinventory',
            name='hsn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='labinventory',
            name='is_liquid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labinventory',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='labinventory',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labinventory',
            name='pack_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='labinventory',
            name='unit',
            field=models.CharField(default='units', max_length=50),
        ),
        migrations.CreateModel(
            name='LabBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('batch_no', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('qty', models.PositiveIntegerField(default=0)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='lab.labinventory')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.labsupplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('supplier_invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('credit_days', models.PositiveIntegerField(default=0)),
                ('purchase_type', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cash_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('courier_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='lab.labsupplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabPurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('batch_no', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('qty', models.PositiveIntegerField()),
                ('free_qty', models.PositiveIntegerField(default=0)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.labbatch')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='lab.labinventory')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab.labpurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
