# Generated by Django 5.2.4 on 2026-01-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_labsupplier_labinventory_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], default='B', max_length=1),
        ),
    ]
