# Generated by Django 5.2.3 on 2026-01-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_labtest_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcharge',
            name='sub_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='sub_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
