# Generated by Django 6.0.2 on 2026-02-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_labcharge_sub_name_labtest_sub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinventory',
            name='items_per_pack',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
