# Generated by Django 5.2.4 on 2026-01-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_pharmacysale_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pharmacystock',
            name='hsn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacystock',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
