# Generated by Django 5.2.4 on 2026-01-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_pharmacystock_gst_percent_pharmacystock_hsn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
