# Generated by Django 5.2.3 on 2026-01-17 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_visit_assigned_role'),
        ('pharmacy', '0006_alter_supplier_address_alter_supplier_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysale',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales', to='patients.patient'),
        ),
    ]
