# Generated by Django 5.2.4 on 2026-01-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_pharmacysale_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysaleitem',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
