# Generated by Django 5.2.4 on 2026-01-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_pharmacysaleitem_gst_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='tablets_per_strip',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='tablets_per_strip',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
