# Generated by Django 5.2.4 on 2026-01-18 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_pharmacystock_tablets_per_strip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
