# Generated by Django 6.0.1 on 2026-01-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_pharmacystock_purchase_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
