# Generated by Django 5.2.4 on 2026-01-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_purchaseitem_gst_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
