# Generated by Django 5.2.4 on 2026-01-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_purchaseitem_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='cash_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='courier_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
