# Generated by Django 5.2.4 on 2026-01-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_pharmacyreturn_pharmacyreturnitem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pharmacystock',
            name='unique_stock_name_batch_exp_supplier',
        ),
        migrations.AddConstraint(
            model_name='pharmacystock',
            constraint=models.UniqueConstraint(fields=('name', 'batch_no'), name='unique_stock_name_batch'),
        ),
    ]
