# Generated by Django 5.2.4 on 2026-01-25 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_remove_pharmacystock_unique_stock_name_batch_exp_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='ptr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
