# Generated by Django 5.2.4 on 2026-01-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_pharmacystock_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=20),
        ),
    ]
