# Generated by Django 5.2.3 on 2026-01-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0017_purchaseinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='cash_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Proportional share of invoke cash discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='(PTR*Qty) - TradeDisc - CashDiscShare', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
