# Generated by Django 5.2.4 on 2026-01-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0018_purchaseitem_cash_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='medicine_type',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('SYRUP', 'Syrup'), ('DROP', 'Drop'), ('INJECTION', 'Injection'), ('GEL', 'Gel'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('POWDER', 'Powder'), ('SPRAY', 'Spray'), ('OTHER', 'Other')], default='TABLET', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='medicine_type',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('SYRUP', 'Syrup'), ('DROP', 'Drop'), ('INJECTION', 'Injection'), ('GEL', 'Gel'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('POWDER', 'Powder'), ('SPRAY', 'Spray'), ('OTHER', 'Other')], default='TABLET', max_length=20),
        ),
    ]
