# Generated by Django 6.0.2 on 2026-02-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0019_pharmacystock_medicine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='category',
            field=models.CharField(choices=[('PHARMACY', 'Pharmacy'), ('CASUALTY', 'Casualty')], default='PHARMACY', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='category',
            field=models.CharField(choices=[('PHARMACY', 'Pharmacy'), ('CASUALTY', 'Casualty')], default='PHARMACY', max_length=20),
        ),
    ]
